---
title: "Visualization_Redesign"
author: "Charles Hendrickson"
date: "2/2/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(ggplot2)
library(lubridate)
library(tidyverse)
```

```{r}
# load data 
sea_ice_data <- read.csv("data/sea_ice.csv")

# Create dataframe
sea_ice_data <- data.frame(sea_ice_data)

# Format date column
sea_ice_data$Date <- mdy(sea_ice_data$Date)
```

```{r}
# Calculate the yearly average sea ice volume 
yearly_avg <- sea_ice_data %>%
  mutate(vol_avg = mean(Vol)) %>% 
  summarize(vol_avg)

```

```{r}
# Visualize sea ice data 
ggplot(data = sea_ice_data, aes(x = Date, y = Vol)) +
  geom_area(fill="lightblue", color="black") +
  geom_smooth(aes(colour="Trend Line")) +
  labs(title = "Arctic Sea Ice Volume (1979-2021)",
       x = "Date",
       y = "Sea Ice Volume (10^3 km^3)") +
  theme_classic() +
  scale_colour_manual(name="Legend", values=("blue"))

```

















































